In [69]:
import numpy as np

a = np.arange(7 * 7).reshape(7, 7)
print(a)
a = a[np.newaxis, :]
a = a[np.newaxis, :]
kernel_shape = (2, 3, 3)
view_shape = a.shape[:-2] + tuple(np.subtract(a.shape[-2:], kernel_shape[-2:]) + 1) + kernel_shape[-2:]
strides = a.strides + a.strides[-2:]
print(view_shape, strides)
sub_matrices = np.lib.stride_tricks.as_strided(a, view_shape, strides)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]
(1, 1, np.int64(5), np.int64(5), 3, 3) (0, 0, 56, 8, 56, 8)


In [68]:

def convolve(input, kernel):
    c = 0
    while len(input) < 4:
        c += 1
        input = input[np.newaxis, :]
    submatrices_shape = input.shape[:-2] + tuple(np.subtract(input.shape[-2:], kernel.shape[-2:]) + 1) + kernel.shape[-2:]
    strides = input.strides + input.strides[-2:]
    sub_matrices = np.lib.stride_tricks.as_strided(input, submatrices_shape, strides)
    sub_matrices = np.rollaxis(sub_matrices, 1, 4)

    convolved = np.einsum('hwnij,oij->hwo', sub_matrices, kernel)
    convolved = np.rollaxis(convolved, 3, 1)
    for _ in range(c):
        convolved = np.squeeze(convolved)
    return convolved

def conv2d(input, filters):
    return Tensor(
        convolve(input.data, filters.data), 
        []
    )

IndentationError: expected an indented block after function definition on line 11 (2772960764.py, line 11)

In [70]:
kf = np.ones(shape=kernel_shape)

In [72]:
sub_matrices = np.rollaxis(sub_matrices, 1, 4)

In [73]:
ans = np.einsum('bhwnij,oij->bhwo', sub_matrices, kf)

In [77]:
ans = np.rollaxis(ans, 3, 1)